name: Ping bot Daily

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "15 12 * * 1-5"
    - cron: "20 12 * * 1-5"
    - cron: "25 12 * * 1-5"
    - cron: "28 12 * * 1-5"
    - cron: "15 00 * * 1-5"
    - cron: "18 00 * * 1-5"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Información del workflow
        run: |
          echo "=== INICIO DEL WORKFLOW ==="
          echo "Evento que triggeró el workflow: ${{ github.event_name }}"
          echo "SHA del commit: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ejecutado por: ${{ github.actor }}"
          echo "========================"
      
      - name: Debug - Información de tiempo y zona horaria
        run: |
          echo "=== INFORMACIÓN DE TIEMPO ==="
          echo "Fecha y hora actual (UTC): $(date -u)"
          echo "Fecha y hora actual (local): $(date)"
          echo "Zona horaria: $(cat /etc/timezone 2>/dev/null || echo "No disponible")"
          echo "Timestamp: $(date +%s)"
          echo "========================"
      
      - name: Debug - Información de red
        run: |
          echo "=== INFORMACIÓN DE RED ==="
          echo "URL de destino: https://pnt-bot-discord.onrender.com/health"
          echo "Resolución DNS:"
          nslookup pnt-bot-discord.onrender.com || echo "DNS lookup falló"
          echo "Prueba de conectividad:"
          ping -c 2 pnt-bot-discord.onrender.com || echo "Ping falló"
          echo "========================"
      
      - name: Ping /health con verbose logging
        run: |
          echo "=== INICIANDO PING A /health ==="
          echo "Timestamp antes del curl: $(date)"
          
          # Curl con opciones detalladas
          curl -v \
               --max-time 30 \
               --retry 2 \
               --retry-delay 5 \
               --write-out "\n=== CURL STATS ===\nTiempo total: %{time_total}s\nCódigo HTTP: %{http_code}\nTamaño descarga: %{size_download} bytes\nRedirecciones: %{num_redirects}\n================\n" \
               https://pnt-bot-discord.onrender.com/health
          
          EXIT_CODE=$?
          echo "=== RESULTADO DEL PING ==="
          echo "Exit code de curl: $EXIT_CODE"
          echo "Timestamp después del curl: $(date)"
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ PING EXITOSO"
          else
            echo "❌ PING FALLIDO - Exit code: $EXIT_CODE"
            echo "Posibles causas:"
            echo "  - 6: No se pudo resolver el host"
            echo "  - 7: No se pudo conectar"
            echo "  - 28: Timeout"
            echo "  - Otro: Ver documentación de curl"
          fi
          echo "========================"
      
      - name: Finalización del workflow
        run: |
          echo "=== WORKFLOW COMPLETADO ==="
          echo "Timestamp final: $(date)"
          echo "Duración aproximada: Ver logs de GitHub Actions"
          echo "========================"