name: Ping bot Daily

on:
  push:
    branches: [ main ]     # fuerza detección al hacer un commit/push
  workflow_dispatch: {}     # te deja correrlo a mano
  schedule:
    # 09:15 / 09:20 / 09:25 AR (UTC-3) => 12:15 / 12:20 / 12:25 UTC
    - cron: "08 23 * * 1-5"
    - cron: "10 23 * * 1-5"
    - cron: "12 23 * * 1-5"
    - cron: "14 23 * * 1-5"
    - cron: "16 23 * * 1-5"
    - cron: "18 23 * * 1-5"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health
        run: curl -sSf https://pnt-bot-discord.onrender.com/health
